PYUIC=pyuic5
.PHONY: ui

ui: 
	$(PYUIC) "ui/connecthostdialog.ui" -o "dialogs/ui_connecthostdialog.py"
	$(PYUIC) "ui/helpwidget.ui" -o "dialogs/ui_helpwidget.py"
	$(PYUIC) "ui/mainwindow.ui" -o "dialogs/ui_mainwindow.py"
	$(PYUIC) "ui/selecthostdialog.ui" -o "dialogs/ui_selecthostdialog.py"
	$(PYUIC) "widgets/ammocount/ui/ammocountwidget.ui" -o "widgets/ammocount/ui_ammocountwidget.py"
	$(PYUIC) "widgets/autodoc/ui/autodocsettingsdialog.ui" -o "widgets/autodoc/ui_autodocsettingsdialog.py"
	$(PYUIC) "widgets/autodoc/ui/autodocwidget.ui" -o "widgets/autodoc/ui_autodocwidget.py"
	$(PYUIC) "widgets/databrowser/ui/databrowser.ui" -o "widgets/databrowser/ui_databrowser.py"
	$(PYUIC) "widgets/dataupdatelogger/ui/dataupdatelogger.ui" -o "widgets/dataupdatelogger/ui_dataupdatelogger.py"
	$(PYUIC) "widgets/datetime/ui/datetimewidget.ui" -o "widgets/datetime/ui_datetimewidget.py"
	$(PYUIC) "widgets/doctorsbag/ui/doctorsbagwidget.ui" -o "widgets/doctorsbag/ui_doctorsbagwidget.py"
	$(PYUIC) "widgets/effects/ui/effectwidget.ui" -o "widgets/effects/ui_effectwidget.py"
	$(PYUIC) "widgets/equippedandgrenades/ui/equippedandgrenadeswidget.ui" -o "widgets/equippedandgrenades/ui_equippedandgrenadeswidget.py"
	$(PYUIC) "widgets/gamestats/ui/gamestatswidget.ui" -o "widgets/gamestats/ui_gamestatswidget.py"
	$(PYUIC) "widgets/inventorybrowser/ui/inventorybrowser.ui" -o "widgets/inventorybrowser/ui_inventorybrowser.py"
	$(PYUIC) "widgets/inventorybrowser/ui/invTabTable.ui" -o "widgets/inventorybrowser/ui_invTabTable.py"
	$(PYUIC) "widgets/locationbrowser/ui/locationbrowser.ui" -o "widgets/locationbrowser/ui_locationbrowser.py"
	$(PYUIC) "widgets/map/ui/editnotedialog.ui" -o "widgets/map/ui_editnotedialog.py"
	$(PYUIC) "widgets/map/ui/editpoidialog.ui" -o "widgets/map/ui_editpoidialog.py"
	$(PYUIC) "widgets/map/ui/globalmapwidget.ui" -o "widgets/map/ui_globalmapwidget.py"
	$(PYUIC) "widgets/map/ui/localmapwidget.ui" -o "widgets/map/ui_localmapwidget.py"
	$(PYUIC) "widgets/perks/ui/perkswidget.ui" -o "widgets/perks/ui_perkswidget.py"
	$(PYUIC) "widgets/playerinfo/ui/playerconditionwidget.ui" -o "widgets/playerinfo/ui_playerconditionwidget.py"
	$(PYUIC) "widgets/playerinfo/ui/playerinfowidget.ui" -o "widgets/playerinfo/ui_playerinfowidget.py"
	$(PYUIC) "widgets/playerstats/ui/limbwidget.ui" -o "widgets/playerstats/ui_limbwidget.py"
	$(PYUIC) "widgets/playerstats/ui/specialwidget.ui" -o "widgets/playerstats/ui_specialwidget.py"
	$(PYUIC) "widgets/playerstats/ui/statswidget.ui" -o "widgets/playerstats/ui_statswidget.py"
	$(PYUIC) "widgets/quests/ui/questswidget.ui" -o "widgets/quests/ui_questswidget.py"
	$(PYUIC) "widgets/quickaid/ui/quickaidwidget.ui" -o "widgets/quickaid/ui_quickaidwidget.py"
	$(PYUIC) "widgets/radio/ui/radiowidget.ui" -o "widgets/radio/ui_radiowidget.py"
	$(PYUIC) "widgets/smallplayerinfo/ui/smallplayerinfowidget.ui" -o "widgets/smallplayerinfo/ui_smallplayerinfowidget.py"
	$(PYUIC) "widgets/workshops/ui/workshopswidget.ui" -o "widgets/workshops/ui_workshopswidget.py"
	